In [400]:
import pandas as pd
import numpy as np
df=pd.read_csv(r'boundary_path_updated.csv')
df.head(2)

,Unnamed: 0,path,count,proportion,path id,label_0.2_2,label_0.2_3,label_0.2_4,label_0.25_2,label_0.25_3,...,label_0.3_4,label_0.35_2,label_0.35_3,label_0.35_4,label_0.4_2,label_0.4_3,label_0.4_4,label_0.45_2,label_0.45_3,label_0.45_4
0,0,"[1042310505, 1050510634, 1063410589, 105891057...",455,0.290921,p1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,"[1042310570, 1057010615, 1061510755, 107551061...",308,0.196931,p2,1,1,1,1,1,...,1,1,1,1,0,0,0,0,0,0

In [401]:
# type(df['path'][0])
# arr=df['path'][0].strip('[]')##bc the original value stuctured as a string with '[]'
# print(arr)

In [402]:
for i in range(len(df['path'])):
    df['path'][i]=df['path'][i].strip('[]')
    df['path'][i]=df['path'][i].split(',')

/Users/Claire/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/Claire/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [403]:
print(df['path'].head(5))
print(df['path id'].head(2))

0    [1042310505,  1050510634,  1063410589,  105891...
1    [1042310570,  1057010615,  1061510755,  107551...
2    [1042310505,  1050510634,  1063410589,  105891...
3    [1042310505,  1050510634,  1063410589,  105891...
4    [1042310505,  1050510634,  1063410589,  105891...
Name: path, dtype: object
0    p1
1    p2
Name: path id, dtype: object

In [404]:
df.head(2)

,Unnamed: 0,path,count,proportion,path id,label_0.2_2,label_0.2_3,label_0.2_4,label_0.25_2,label_0.25_3,...,label_0.3_4,label_0.35_2,label_0.35_3,label_0.35_4,label_0.4_2,label_0.4_3,label_0.4_4,label_0.45_2,label_0.45_3,label_0.45_4
0,0,"[1042310505, 1050510634, 1063410589, 105891...",455,0.290921,p1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,"[1042310570, 1057010615, 1061510755, 107551...",308,0.196931,p2,1,1,1,1,1,...,1,1,1,1,0,0,0,0,0,0

In [413]:
df_new=pd.DataFrame()
path_id=[]
links=[]
for i in range(len(df['path'])):##62
    for j in range(len(df['path'][i])):
        path_id.append(df['path id'][i])
        links.append(df['path'][i][j])

In [414]:
df_new['path_id']=path_id
df_new['link']=links

In [416]:
df_new.head(3)

  path_id         link
0      p1   1042310505
1      p1   1050510634
2      p1   1063410589

In [417]:
df_new.to_csv('path_links.csv')